[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
# make it compatible with black
profile = "black"
line_length = 120

[[tool.mypy.overrides]]
module = "nltk.*"
ignore_missing_imports = true

[tool.poetry]
name = "silnlp"
version = "1.0.0"
description = ""
authors = ["SIL International"]

[tool.poetry.scripts]
silnlp-extract-corpora = "silnlp.common.extract_corpora:main"

silnlp-nmt-preprocess = "silnlp.nmt.preprocess:main"
silnlp-nmt-train = "silnlp.nmt.train:main"
silnlp-nmt-test = "silnlp.nmt.test:main"
silnlp-nmt-translate = "silnlp.nmt.translate:main"

silnlp-alignment-preprocess = "silnlp.alignment.preprocess:main"
silnlp-alignment-align = "silnlp.alignment.align:main"
silnlp-alignment-test = "silnlp.alignment.test:main"
silnlp-alignment-aggregate-results = "silnlp.alignment.aggregate_results:main"

clowder = "clowder.clowder:main"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pandas = "^2.2"
sentencepiece = "^0.1.97"
nltk = "^3.5"
python-dotenv = "0.20.0"
seaborn = "0.11.2"
morfessor = "^2.0.6"
Morfessor-FlatCat = "^1.0.8"
psutil = "^5.7.3"
scikit-learn = "^1.1.2"
numpy = "^1.26.0"
lit-nlp = "0.4.1"
google-cloud-translate = "^3.0.2"
scipy = "^1.11.2"
clearml = ">=1.4.1"
XlsxWriter = "^3.2.0"
python-Levenshtein = "^0.27.1"
lxml = "^4.6.3"
tqdm = "^4.62.2"
sacrebleu = "^2.3.1"
ctranslate2 = "^3.5.1"
libclang = "14.0.6"
sil-machine = {extras = ["thot"], version = "1.7.2"}
datasets = "^2.7.1"
torch = {version = "^2.4", source = "torch"}
sacremoses = "^0.0.53"
evaluate = "^0.3.0"
python-docx = "^0.8.11"
iso639-lang = "^2.1.0"
eflomal = { version = "^2.0.0", optional = true }
accelerate = "^0.26.0"
transformers = "^4.46"
optimum = "^1.16.0"
google = "^3.0.0"
google-api-python-client = "^2.101.0"
google-auth-httplib2 = "^0.1.1"
google-auth-oauthlib = "^1.0.0"
oauth2client = "^4.1.3"
gspread = "^5.11.2"
pydrive2 = "^1.17.0"
jinja2 = "^3.1.2"
peft = "0.8.0"
typer = "^0.9.0"
rich = "^13.7.0"
gspread-dataframe = "^3.3.1"
attrs = "^22.2.0"
jsonschema = "^4.18.0"
requests = "^2.31"
openpyxl = "^3.1.2"
packaging = "^22.0"
hanzidentifier = "^1.2.0"
jarowinkler = "^2.0.1"

[tool.poetry.group.dev.dependencies]
types-pyyaml = "^6.0.12.12"
black = "^22.6.0"
flake8 = "^3.9.0"
ipykernel = "^6.4.1"
pylint = "^2.8.3"
pytest = "^6.2.4"
types-tqdm = "^4.62.4"
pandas-stubs = "^1.0.4"
types-regex = "^2023.10.3.0"
lxml-stubs = "^0.4.0"
mypy = "^1.7.1"

[tool.poetry.extras]
eflomal = ["eflomal"]

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

