# These are the NLLB language codes
NLLB_TAGS = [
    "ace_Arab",
    "ace_Latn",
    "acm_Arab",
    "acq_Arab",
    "aeb_Arab",
    "afr_Latn",
    "ajp_Arab",
    "aka_Latn",
    "amh_Ethi",
    "apc_Arab",
    "arb_Arab",
    "ars_Arab",
    "ary_Arab",
    "arz_Arab",
    "asm_Beng",
    "ast_Latn",
    "awa_Deva",
    "ayr_Latn",
    "azb_Arab",
    "azj_Latn",
    "bak_Cyrl",
    "bam_Latn",
    "ban_Latn",
    "bel_Cyrl",
    "bem_Latn",
    "ben_Beng",
    "bho_Deva",
    "bjn_Arab",
    "bjn_Latn",
    "bod_Tibt",
    "bos_Latn",
    "bug_Latn",
    "bul_Cyrl",
    "cat_Latn",
    "ceb_Latn",
    "ces_Latn",
    "cjk_Latn",
    "ckb_Arab",
    "crh_Latn",
    "cym_Latn",
    "dan_Latn",
    "deu_Latn",
    "dik_Latn",
    "dyu_Latn",
    "dzo_Tibt",
    "ell_Grek",
    "eng_Latn",
    "epo_Latn",
    "est_Latn",
    "eus_Latn",
    "ewe_Latn",
    "fao_Latn",
    "pes_Arab",
    "fij_Latn",
    "fin_Latn",
    "fon_Latn",
    "fra_Latn",
    "fur_Latn",
    "fuv_Latn",
    "gla_Latn",
    "gle_Latn",
    "glg_Latn",
    "grn_Latn",
    "guj_Gujr",
    "hat_Latn",
    "hau_Latn",
    "heb_Hebr",
    "hin_Deva",
    "hne_Deva",
    "hrv_Latn",
    "hun_Latn",
    "hye_Armn",
    "ibo_Latn",
    "ilo_Latn",
    "ind_Latn",
    "isl_Latn",
    "ita_Latn",
    "jav_Latn",
    "jpn_Jpan",
    "kab_Latn",
    "kac_Latn",
    "kam_Latn",
    "kan_Knda",
    "kas_Arab",
    "kas_Deva",
    "kat_Geor",
    "knc_Arab",
    "knc_Latn",
    "kaz_Cyrl",
    "kbp_Latn",
    "kea_Latn",
    "khm_Khmr",
    "kik_Latn",
    "kin_Latn",
    "kir_Cyrl",
    "kmb_Latn",
    "kon_Latn",
    "kor_Hang",
    "kmr_Latn",
    "lao_Laoo",
    "lvs_Latn",
    "lij_Latn",
    "lim_Latn",
    "lin_Latn",
    "lit_Latn",
    "lmo_Latn",
    "ltg_Latn",
    "ltz_Latn",
    "lua_Latn",
    "lug_Latn",
    "luo_Latn",
    "lus_Latn",
    "mag_Deva",
    "mai_Deva",
    "mal_Mlym",
    "mar_Deva",
    "min_Latn",
    "mkd_Cyrl",
    "plt_Latn",
    "mlt_Latn",
    "mni_Beng",
    "khk_Cyrl",
    "mos_Latn",
    "mri_Latn",
    "zsm_Latn",
    "mya_Mymr",
    "nld_Latn",
    "nno_Latn",
    "nob_Latn",
    "npi_Deva",
    "nso_Latn",
    "nus_Latn",
    "nya_Latn",
    "oci_Latn",
    "gaz_Latn",
    "ory_Orya",
    "pag_Latn",
    "pan_Guru",
    "pap_Latn",
    "pol_Latn",
    "por_Latn",
    "prs_Arab",
    "pbt_Arab",
    "quy_Latn",
    "ron_Latn",
    "run_Latn",
    "rus_Cyrl",
    "sag_Latn",
    "san_Deva",
    "sat_Beng",
    "scn_Latn",
    "shn_Mymr",
    "sin_Sinh",
    "slk_Latn",
    "slv_Latn",
    "smo_Latn",
    "sna_Latn",
    "snd_Arab",
    "som_Latn",
    "sot_Latn",
    "spa_Latn",
    "als_Latn",
    "srd_Latn",
    "srp_Cyrl",
    "ssw_Latn",
    "sun_Latn",
    "swe_Latn",
    "swh_Latn",
    "szl_Latn",
    "tam_Taml",
    "tat_Cyrl",
    "tel_Telu",
    "tgk_Cyrl",
    "tgl_Latn",
    "tha_Thai",
    "tir_Ethi",
    "taq_Latn",
    "taq_Tfng",
    "tpi_Latn",
    "tsn_Latn",
    "tso_Latn",
    "tuk_Latn",
    "tum_Latn",
    "tur_Latn",
    "twi_Latn",
    "tzm_Tfng",
    "uig_Arab",
    "ukr_Cyrl",
    "umb_Latn",
    "urd_Arab",
    "uzn_Latn",
    "vec_Latn",
    "vie_Latn",
    "war_Latn",
    "wol_Latn",
    "xho_Latn",
    "ydd_Hebr",
    "yor_Latn",
    "yue_Hant",
    "zho_Hans",
    "zho_Hant",
    "zul_Latn",
]

NLLB_ISO_SET = set(tag.split("_")[0] for tag in NLLB_TAGS)
NLLB_SCRIPT_SET = set(tag.split("_")[1] for tag in NLLB_TAGS)

# nllb_iso_codes  = ['ace', 'acm', 'acq', 'aeb', 'afr', 'ajp', 'aka', 'als', 'amh', 'apc', 'arb', 'ars', 'ary', 'arz', 'asm', 'ast', 'awa', 'ayr', 'azb', 'azj', 'bak', 'bam', 'ban', 'bel', 'bem', 'ben', 'bho', 'bjn', 'bod', 'bos', 'bug', 'bul', 'cat', 'ceb', 'ces', 'cjk', 'ckb', 'crh', 'cym', 'dan', 'deu', 'dik', 'dyu', 'dzo', 'ell', 'eng', 'epo', 'est', 'eus', 'ewe', 'fao', 'fij', 'fin', 'fon', 'fra', 'fur', 'fuv', 'gaz', 'gla', 'gle', 'glg', 'grn', 'guj', 'hat', 'hau', 'heb', 'hin', 'hne', 'hrv', 'hun', 'hye', 'ibo', 'ilo', 'ind', 'isl', 'ita', 'jav', 'jpn', 'kab', 'kac', 'kam', 'kan', 'kas', 'kat', 'kaz', 'kbp', 'kea', 'khk', 'khm', 'kik', 'kin', 'kir', 'kmb', 'kmr', 'knc', 'kon', 'kor', 'lao', 'lij', 'lim', 'lin', 'lit', 'lmo', 'ltg', 'ltz', 'lua', 'lug', 'luo', 'lus', 'lvs', 'mag', 'mai', 'mal', 'mar', 'min', 'mkd', 'mlt', 'mni', 'mos', 'mri', 'mya', 'nld', 'nno', 'nob', 'npi', 'nso', 'nus', 'nya', 'oci', 'ory', 'pag', 'pan', 'pap', 'pbt', 'pes', 'plt', 'pol', 'por', 'prs', 'quy', 'ron', 'run', 'rus', 'sag', 'san', 'sat', 'scn', 'shn', 'sin', 'slk', 'slv', 'smo', 'sna', 'snd', 'som', 'sot', 'spa', 'srd', 'srp', 'ssw', 'sun', 'swe', 'swh', 'szl', 'tam', 'taq', 'tat', 'tel', 'tgk', 'tgl', 'tha', 'tir', 'tpi', 'tsn', 'tso', 'tuk', 'tum', 'tur', 'twi', 'tzm', 'uig', 'ukr', 'umb', 'urd', 'uzn', 'vec', 'vie', 'war', 'wol', 'xho', 'ydd', 'yor', 'yue', 'zho', 'zsm', 'zul']
# nllb_scripts = ['Arab', 'Armn', 'Beng', 'Cyrl', 'Deva', 'Ethi', 'Geor', 'Grek', 'Gujr', 'Guru', 'Hang', 'Hans', 'Hant', 'Hebr', 'Jpan', 'Khmr', 'Knda', 'Laoo', 'Latn', 'Mlym', 'Mymr', 'Orya', 'Sinh', 'Taml', 'Telu', 'Tfng', 'Thai', 'Tibt']

# These are a selection of 'default' or likely language codes for a given script.
NLLB_TAG_FROM_SCRIPT = {
    "Arab": "arb_Arab",
    "Armn": "hye_Armn",
    "Beng": "ben_Beng",
    "Cyrl": "rus_Cyrl",
    "Deva": "hin_Deva",
    "Ethi": "amh_Ethi",
    "Geor": "kat_Geor",
    "Grek": "ell_Grek",
    "Gujr": "guj_Gujr",
    "Guru": "pan_Guru",
    "Hang": "kor_Hang",
    "Hans": "zho_Hans",
    "Hant": "zho_Hant",
    "Hebr": "heb_Hebr",
    "Jpan": "jpn_Jpan",
    "Khmr": "khm_Khmr",
    "Knda": "kan_Knda",
    "Laoo": "lao_Laoo",
    "Latn": "eng_Latn",
    "Mlym": "mal_Mlym",
    "Mymr": "mya_Mymr",
    "Orya": "ory_Orya",
    "Sinh": "sin_Sinh",
    "Taml": "tam_Taml",
    "Telu": "tel_Telu",
    "Tfng": "tzm_Tfng",
    "Thai": "tha_Thai",
    "Tibt": "bod_Tibt",
}

# These are the most common scripts for each language in NLLB
NLLB_TAG_FROM_ISO = {
    "ace": "ace_Latn",
    "acm": "acm_Arab",
    "acq": "acq_Arab",
    "aeb": "aeb_Arab",
    "afr": "afr_Latn",
    "ajp": "ajp_Arab",
    "aka": "aka_Latn",
    "amh": "amh_Ethi",
    "apc": "apc_Arab",
    "arb": "arb_Arab",
    "ars": "ars_Arab",
    "ary": "ary_Arab",
    "arz": "arz_Arab",
    "asm": "asm_Beng",
    "ast": "ast_Latn",
    "awa": "awa_Deva",
    "ayr": "ayr_Latn",
    "azb": "azb_Arab",
    "azj": "azj_Latn",
    "bak": "bak_Cyrl",
    "bam": "bam_Latn",
    "ban": "ban_Latn",
    "bel": "bel_Cyrl",
    "bem": "bem_Latn",
    "ben": "ben_Beng",
    "bho": "bho_Deva",
    "bjn": "bjn_Latn",
    "bod": "bod_Tibt",
    "bos": "bos_Latn",
    "bug": "bug_Latn",
    "bul": "bul_Cyrl",
    "cat": "cat_Latn",
    "ceb": "ceb_Latn",
    "ces": "ces_Latn",
    "cjk": "cjk_Latn",
    "ckb": "ckb_Arab",
    "crh": "crh_Latn",
    "cym": "cym_Latn",
    "dan": "dan_Latn",
    "deu": "deu_Latn",
    "dik": "dik_Latn",
    "dyu": "dyu_Latn",
    "dzo": "dzo_Tibt",
    "ell": "ell_Grek",
    "eng": "eng_Latn",
    "epo": "epo_Latn",
    "est": "est_Latn",
    "eus": "eus_Latn",
    "ewe": "ewe_Latn",
    "fao": "fao_Latn",
    "pes": "pes_Arab",
    "fij": "fij_Latn",
    "fin": "fin_Latn",
    "fon": "fon_Latn",
    "fra": "fra_Latn",
    "fur": "fur_Latn",
    "fuv": "fuv_Latn",
    "gla": "gla_Latn",
    "gle": "gle_Latn",
    "glg": "glg_Latn",
    "grn": "grn_Latn",
    "guj": "guj_Gujr",
    "hat": "hat_Latn",
    "hau": "hau_Latn",
    "heb": "heb_Hebr",
    "hin": "hin_Deva",
    "hne": "hne_Deva",
    "hrv": "hrv_Latn",
    "hun": "hun_Latn",
    "hye": "hye_Armn",
    "ibo": "ibo_Latn",
    "ilo": "ilo_Latn",
    "ind": "ind_Latn",
    "isl": "isl_Latn",
    "ita": "ita_Latn",
    "jav": "jav_Latn",
    "jpn": "jpn_Jpan",
    "kab": "kab_Latn",
    "kac": "kac_Latn",
    "kam": "kam_Latn",
    "kan": "kan_Knda",
    "kas": "kas_Deva",
    "kat": "kat_Geor",
    "knc": "knc_Latn",
    "kaz": "kaz_Cyrl",
    "kbp": "kbp_Latn",
    "kea": "kea_Latn",
    "khm": "khm_Khmr",
    "kik": "kik_Latn",
    "kin": "kin_Latn",
    "kir": "kir_Cyrl",
    "kmb": "kmb_Latn",
    "kon": "kon_Latn",
    "kor": "kor_Hang",
    "kmr": "kmr_Latn",
    "lao": "lao_Laoo",
    "lvs": "lvs_Latn",
    "lij": "lij_Latn",
    "lim": "lim_Latn",
    "lin": "lin_Latn",
    "lit": "lit_Latn",
    "lmo": "lmo_Latn",
    "ltg": "ltg_Latn",
    "ltz": "ltz_Latn",
    "lua": "lua_Latn",
    "lug": "lug_Latn",
    "luo": "luo_Latn",
    "lus": "lus_Latn",
    "mag": "mag_Deva",
    "mai": "mai_Deva",
    "mal": "mal_Mlym",
    "mar": "mar_Deva",
    "min": "min_Latn",
    "mkd": "mkd_Cyrl",
    "plt": "plt_Latn",
    "mlt": "mlt_Latn",
    "mni": "mni_Beng",
    "khk": "khk_Cyrl",
    "mos": "mos_Latn",
    "mri": "mri_Latn",
    "zsm": "zsm_Latn",
    "mya": "mya_Mymr",
    "nld": "nld_Latn",
    "nno": "nno_Latn",
    "nob": "nob_Latn",
    "npi": "npi_Deva",
    "nso": "nso_Latn",
    "nus": "nus_Latn",
    "nya": "nya_Latn",
    "oci": "oci_Latn",
    "gaz": "gaz_Latn",
    "ory": "ory_Orya",
    "pag": "pag_Latn",
    "pan": "pan_Guru",
    "pap": "pap_Latn",
    "pol": "pol_Latn",
    "por": "por_Latn",
    "prs": "prs_Arab",
    "pbt": "pbt_Arab",
    "quy": "quy_Latn",
    "ron": "ron_Latn",
    "run": "run_Latn",
    "rus": "rus_Cyrl",
    "sag": "sag_Latn",
    "san": "san_Deva",
    "sat": "sat_Beng",
    "scn": "scn_Latn",
    "shn": "shn_Mymr",
    "sin": "sin_Sinh",
    "slk": "slk_Latn",
    "slv": "slv_Latn",
    "smo": "smo_Latn",
    "sna": "sna_Latn",
    "snd": "snd_Arab",
    "som": "som_Latn",
    "sot": "sot_Latn",
    "spa": "spa_Latn",
    "als": "als_Latn",
    "srd": "srd_Latn",
    "srp": "srp_Cyrl",
    "ssw": "ssw_Latn",
    "sun": "sun_Latn",
    "swe": "swe_Latn",
    "swh": "swh_Latn",
    "szl": "szl_Latn",
    "tam": "tam_Taml",
    "tat": "tat_Cyrl",
    "tel": "tel_Telu",
    "tgk": "tgk_Cyrl",
    "tgl": "tgl_Latn",
    "tha": "tha_Thai",
    "tir": "tir_Ethi",
    "taq": "taq_Tfng",
    "tpi": "tpi_Latn",
    "tsn": "tsn_Latn",
    "tso": "tso_Latn",
    "tuk": "tuk_Latn",
    "tum": "tum_Latn",
    "tur": "tur_Latn",
    "twi": "twi_Latn",
    "tzm": "tzm_Tfng",
    "uig": "uig_Arab",
    "ukr": "ukr_Cyrl",
    "umb": "umb_Latn",
    "urd": "urd_Arab",
    "uzn": "uzn_Latn",
    "vec": "vec_Latn",
    "vie": "vie_Latn",
    "war": "war_Latn",
    "wol": "wol_Latn",
    "xho": "xho_Latn",
    "ydd": "ydd_Hebr",
    "yor": "yor_Latn",
    "yue": "yue_Hant",
    "zho": "zho_Hant",
    "zul": "zul_Latn",
}

# These NLLB Languages use a latin script:
NLLB_LATIN_SCRIPT_ISOS = [
    "ace",
    "afr",
    "aka",
    "ast",
    "ayr",
    "azj",
    "bam",
    "ban",
    "bem",
    "bjn",
    "bos",
    "bug",
    "cat",
    "ceb",
    "ces",
    "cjk",
    "crh",
    "cym",
    "dan",
    "deu",
    "dik",
    "dyu",
    "eng",
    "epo",
    "est",
    "eus",
    "ewe",
    "fao",
    "fij",
    "fin",
    "fon",
    "fra",
    "fur",
    "fuv",
    "gla",
    "gle",
    "glg",
    "grn",
    "hat",
    "hau",
    "hrv",
    "hun",
    "ibo",
    "ilo",
    "ind",
    "isl",
    "ita",
    "jav",
    "kab",
    "kac",
    "kam",
    "knc",
    "kbp",
    "kea",
    "kik",
    "kin",
    "kmb",
    "kon",
    "kmr",
    "lvs",
    "lij",
    "lim",
    "lin",
    "lit",
    "lmo",
    "ltg",
    "ltz",
    "lua",
    "lug",
    "luo",
    "lus",
    "min",
    "plt",
    "mlt",
    "mos",
    "mri",
    "zsm",
    "nld",
    "nno",
    "nob",
    "nso",
    "nus",
    "nya",
    "oci",
    "gaz",
    "pag",
    "pap",
    "pol",
    "por",
    "quy",
    "ron",
    "run",
    "sag",
    "scn",
    "slk",
    "slv",
    "smo",
    "sna",
    "som",
    "sot",
    "spa",
    "als",
    "srd",
    "ssw",
    "sun",
    "swe",
    "swh",
    "szl",
    "tgl",
    "taq",
    "tpi",
    "tsn",
    "tso",
    "tuk",
    "tum",
    "tur",
    "twi",
    "umb",
    "uzn",
    "vec",
    "vie",
    "war",
    "wol",
    "xho",
    "yor",
    "zul",
]

# NLLB languages with text in eBible
NLLB_TAG_WITH_DATA_IN_EBIBLE = [
    "aka_Latn",
    "arb_Arab",
    "asm_Beng",
    "azb_Arab",
    "bel_Cyrl",
    "ben_Beng",
    "ceb_Latn",
    "ces_Latn",
    "ckb_Arab",
    "dan_Latn",
    "deu_Latn",
    "dik_Latn",
    "eng_Latn",
    "epo_Latn",
    "ewe_Latn",
    "pes_Arab",
    "fra_Latn",
    "guj_Gujr",
    "hat_Latn",
    "hau_Latn",
    "heb_Hebr",
    "hin_Deva",
    "hrv_Latn",
    "hun_Latn",
    "ilo_Latn",
    "ind_Latn",
    "ita_Latn",
    "jpn_Jpan",
    "kan_Knda",
    "kik_Latn",
    "lin_Latn",
    "lit_Latn",
    "lug_Latn",
    "luo_Latn",
    "mal_Mlym",
    "mar_Deva",
    "mya_Mymr",
    "nld_Latn",
    "npi_Deva",
    "nya_Latn",
    "ory_Orya",
    "pan_Guru",
    "pol_Latn",
    "por_Latn",
    "ron_Latn",
    "rus_Cyrl",
    "san_Deva",
    "som_Latn",
    "spa_Latn",
    "als_Latn",
    "srp_Cyrl",
    "swe_Latn",
    "swh_Latn",
    "tam_Taml",
    "tel_Telu",
    "tgk_Cyrl",
    "tgl_Latn",
    "tha_Thai",
    "tpi_Latn",
    "tur_Latn",
    "twi_Latn",
    "uig_Arab",
    "ukr_Cyrl",
    "urd_Arab",
    "vie_Latn",
    "wol_Latn",
    "yor_Latn",
]


class BidiDict:
    def __init__(self, data):
        self.data = {**{k: v for k, v in data}, **{v: k for k, v in data}}

    def get_alternative(self, isocode):
        return self.data.get(isocode)

data = [
    ("aar", "aa"),
    ("abk", "ab"),
    ("afr", "af"),
    ("aka", "ak"),
    ("alb", "sq"),
    ("amh", "am"),
    ("ara", "ar"),
    ("arg", "an"),
    ("arm", "hy"),
    ("asm", "as"),
    ("ava", "av"),
    ("ave", "ae"),
    ("aym", "ay"),
    ("aze", "az"),
    ("bak", "ba"),
    ("bam", "bm"),
    ("baq", "eu"),
    ("bel", "be"),
    ("ben", "bn"),
    ("bis", "bi"),
    ("bod", "bo"),
    ("bos", "bs"),
    ("bre", "br"),
    ("bul", "bg"),
    ("bur", "my"),
    ("cat", "ca"),
    ("ces", "cs"),
    ("cha", "ch"),
    ("che", "ce"),
    ("chi", "zh"),
    ("chu", "cu"),
    ("chv", "cv"),
    ("cor", "kw"),
    ("cos", "co"),
    ("cre", "cr"),
    ("cym", "cy"),
    ("cze", "cs"),
    ("dan", "da"),
    ("deu", "de"),
    ("div", "dv"),
    ("dut", "nl"),
    ("dzo", "dz"),
    ("ell", "el"),
    ("eng", "en"),
    ("est", "et"),
    ("eus", "eu"),
    ("ewe", "ee"),
    ("fao", "fo"),
    ("fas", "fa"),
    ("fij", "fj"),
    ("fin", "fi"),
    ("fra", "fr"),
    ("fre", "fr"),
    ("fry", "fy"),
    ("ful", "ff"),
    ("geo", "ka"),
    ("ger", "de"),
    ("gla", "gd"),
    ("gle", "ga"),
    ("glg", "gl"),
    ("glv", "gv"),
    ("gre", "el"),
    ("grn", "gn"),
    ("guj", "gu"),
    ("hat", "ht"),
    ("hau", "ha"),
    ("hbs", "sh"),
    ("heb", "he"),
    ("her", "hz"),
    ("hin", "hi"),
    ("hmo", "ho"),
    ("hrv", "hr"),
    ("hun", "hu"),
    ("hye", "hy"),
    ("ibo", "ig"),
    ("ice", "is"),
    ("iii", "ii"),
    ("iku", "iu"),
    ("ind", "id"),
    ("ipk", "ik"),
    ("isl", "is"),
    ("ita", "it"),
    ("jav", "jv"),
    ("jpn", "ja"),
    ("kal", "kl"),
    ("kan", "kn"),
    ("kas", "ks"),
    ("kat", "ka"),
    ("kau", "kr"),
    ("kaz", "kk"),
    ("khm", "km"),
    ("kik", "ki"),
    ("kin", "rw"),
    ("kir", "ky"),
    ("kom", "kv"),
    ("kon", "kg"),
    ("kor", "ko"),
    ("kua", "kj"),
    ("kur", "ku"),
    ("lao", "lo"),
    ("lat", "la"),
    ("lav", "lv"),
    ("lim", "li"),
    ("lin", "ln"),
    ("lit", "lt"),
    ("ltz", "lb"),
    ("lub", "lu"),
    ("lug", "lg"),
    ("mac", "mk"),
    ("mah", "mh"),
    ("mal", "ml"),
    ("mao", "mi"),
    ("mar", "mr"),
    ("may", "ms"),
    ("mkd", "mk"),
    ("mlg", "mg"),
    ("mlt", "mt"),
    ("mon", "mn"),
    ("mri", "mi"),
    ("msa", "ms"),
    ("mya", "my"),
    ("nau", "na"),
    ("nav", "nv"),
    ("nbl", "nr"),
    ("nde", "nd"),
    ("ndo", "ng"),
    ("nep", "ne"),
    ("nld", "nl"),
    ("nno", "nn"),
    ("nob", "nb"),
    ("nor", "no"),
    ("nya", "ny"),
    ("oci", "oc"),
    ("oji", "oj"),
    ("ori", "or"),
    ("orm", "om"),
    ("oss", "os"),
    ("pan", "pa"),
    ("per", "fa"),
    ("pli", "pi"),
    ("pol", "pl"),
    ("por", "pt"),
    ("pus", "ps"),
    ("que", "qu"),
    ("roh", "rm"),
    ("ron", "ro"),
    ("rum", "ro"),
    ("run", "rn"),
    ("rus", "ru"),
    ("sag", "sg"),
    ("san", "sa"),
    ("sin", "si"),
    ("slk", "sk"),
    ("slo", "sk"),
    ("slv", "sl"),
    ("sme", "se"),
    ("smo", "sm"),
    ("sna", "sn"),
    ("snd", "sd"),
    ("som", "so"),
    ("sot", "st"),
    ("spa", "es"),
    ("sqi", "sq"),
    ("srd", "sc"),
    ("srp", "sr"),
    ("ssw", "ss"),
    ("sun", "su"),
    ("swa", "sw"),
    ("swe", "sv"),
    ("tah", "ty"),
    ("tam", "ta"),
    ("tat", "tt"),
    ("tel", "te"),
    ("tgk", "tg"),
    ("tgl", "tl"),
    ("tha", "th"),
    ("tib", "bo"),
    ("tir", "ti"),
    ("ton", "to"),
    ("tsn", "tn"),
    ("tso", "ts"),
    ("tuk", "tk"),
    ("tur", "tr"),
    ("twi", "tw"),
    ("uig", "ug"),
    ("ukr", "uk"),
    ("urd", "ur"),
    ("uzb", "uz"),
    ("ven", "ve"),
    ("vie", "vi"),
    ("wel", "cy"),
    ("wln", "wa"),
    ("wol", "wo"),
    ("xho", "xh"),
    ("yid", "yi"),
    ("yor", "yo"),
    ("zha", "za"),
    ("zho", "zh"),
    ("zul", "zu"),
]

# Create the bidirectional dictionary
ALT_ISO = BidiDict(data)

# Get or check whether any two or three letter iso code has an alternative:
# alt_iso = ALT_ISO.get_alternative(isocode)
