from pathlib import Path

from silnlp.nmt.config_utils import load_config
from tests.smoke_tests.smoke_test_utils import (
    PREPROCESS_OUTPUT_PATTERNS,
    TEST_MT_DIR,
    delete_generated_paths,
    read_lines,
    set_up_environment,
)

EXPERIMENT_NAME = "test_preprocess"

# The data sets that the preprocess step is expected to create from the corpora in the bucket. If
# the corpora or the experiment's config change, these files have to be regenerated by running the
# preprocess step and copying its output into this directory.
EXPECTED_OUTPUTS_DIR = TEST_MT_DIR / "expected_outputs" / EXPERIMENT_NAME

# The experiment's tokenizer, which the train, test and translate steps all use, is also saved to
# the experiment directory. Its files are too large to store as expected output, so only their
# existence is checked.
TOKENIZER_FILE_NAMES = [
    "tokenizer.json",
    "tokenizer_config.json",
    "special_tokens_map.json",
    "sentencepiece.bpe.model",
]

# The tokenization statistics are written as both a CSV file, which is compared against the
# expected output, and a spreadsheet, which is a binary file, so only its existence is checked.
TOKENIZATION_STATS_SPREADSHEET_FILE_NAME = "tokenization_stats.xlsx"


def test_preprocess_creates_data_sets():
    # Preprocessing does not use the model, so there is nothing expensive to mock here: the whole
    # step is run against the real corpora.
    environment = set_up_environment()
    exp_dir = environment.get_mt_exp_dir(EXPERIMENT_NAME)
    delete_generated_paths(exp_dir, PREPROCESS_OUTPUT_PATTERNS)

    config = load_config(EXPERIMENT_NAME, environment)
    config.set_seed()
    # The tokenization statistics are only created when stats is set, as the --stats option does
    config.preprocess(stats=True, force_align=False)

    check_expected_outputs(exp_dir)
    check_tokenizer_files_exist(exp_dir)
    check_no_other_files_were_created(exp_dir)

    delete_generated_paths(exp_dir, PREPROCESS_OUTPUT_PATTERNS)


def check_expected_outputs(exp_dir: Path):
    for expected_output_path in sorted(EXPECTED_OUTPUTS_DIR.iterdir()):
        actual_path = exp_dir / expected_output_path.name
        assert actual_path.is_file(), f"{expected_output_path.name} was not created"
        assert read_lines(actual_path) == read_lines(expected_output_path), expected_output_path.name


def check_tokenizer_files_exist(exp_dir: Path):
    for file_name in TOKENIZER_FILE_NAMES:
        assert (exp_dir / file_name).is_file()


def check_no_other_files_were_created(exp_dir: Path):
    # Any file that the preprocess step starts creating has to be added to the expected output
    expected_file_names = {path.name for path in EXPECTED_OUTPUTS_DIR.iterdir()}
    expected_file_names.update(TOKENIZER_FILE_NAMES)
    expected_file_names.add(TOKENIZATION_STATS_SPREADSHEET_FILE_NAME)

    created_file_names = {path.name for path in exp_dir.iterdir()} - {"config.yml"}
    assert created_file_names == expected_file_names
