import math
from pathlib import Path
from typing import Dict, List

import pytest

from silnlp.common.environment import SilNlpEnv
from silnlp.nmt.config_utils import load_config
from silnlp.nmt.translate import TranslationTask
from tests.smoke_tests.mock_pretrained_model import (
    FixedTranslationPreTrainedModelProviderFactory,
    mock_sequence_log_prob,
)
from tests.smoke_tests.smoke_test_utils import (
    TRANSLATE_OUTPUT_PATTERNS,
    create_model_with_mock_pretrained_model,
    delete_generated_paths,
    read_lines,
    set_up_environment,
)

EXPERIMENT_NAME = "test_translate"

# The step of the checkpoint directory that is stored in the experiment directory. The translate
# step resolves the last checkpoint from the directory names under run/, so the step is also the
# name of the directory that the drafts are written to.
CHECKPOINT_STEP = 2

BOOK = "3JN"
BOOK_NUMBER = "65"
SOURCE_PROJECT = "BSB"
SOURCE_FILE_NAME = "input_sentences.txt"


def test_translate_book():
    environment = set_up_environment()
    exp_dir = environment.get_mt_exp_dir(EXPERIMENT_NAME)
    delete_generated_paths(exp_dir, TRANSLATE_OUTPUT_PATTERNS)

    # Inferencing is done by a mock model that "translates" every sentence to the same fixed
    # sentence, so the content of the draft is known.
    model_provider_factory = FixedTranslationPreTrainedModelProviderFactory()
    translation_task = create_translation_task(environment, model_provider_factory)

    translation_task.translate_books(
        books=BOOK,
        src_project=SOURCE_PROJECT,
        trg_project=None,
        trg_iso=None,
        save_confidences=True,
        postprocess_handler=None,
        vref=True,
    )

    check_last_checkpoint_was_used(model_provider_factory, exp_dir)
    num_verses = check_book_draft(exp_dir, model_provider_factory.translation)
    check_vref_export(exp_dir, num_verses)
    check_book_confidences(exp_dir, num_verses)

    delete_generated_paths(exp_dir, TRANSLATE_OUTPUT_PATTERNS)


def test_translate_text_file():
    environment = set_up_environment()
    exp_dir = environment.get_mt_exp_dir(EXPERIMENT_NAME)
    delete_generated_paths(exp_dir, TRANSLATE_OUTPUT_PATTERNS)
    num_sentences = len(read_lines(exp_dir / SOURCE_FILE_NAME))

    model_provider_factory = FixedTranslationPreTrainedModelProviderFactory()
    translation_task = create_translation_task(environment, model_provider_factory)

    translation_task.translate_files(
        src=SOURCE_FILE_NAME,
        trg=None,
        src_iso=None,
        trg_iso=None,
        save_confidences=True,
        postprocess_handler=None,
    )

    check_last_checkpoint_was_used(model_provider_factory, exp_dir)
    check_text_file_draft(exp_dir, num_sentences, model_provider_factory.translation)
    check_text_file_confidences(exp_dir, num_sentences)

    delete_generated_paths(exp_dir, TRANSLATE_OUTPUT_PATTERNS)


def create_translation_task(
    environment: SilNlpEnv, model_provider_factory: FixedTranslationPreTrainedModelProviderFactory
) -> TranslationTask:
    # The translation task seeds the config and resolves the checkpoint itself
    config = load_config(EXPERIMENT_NAME, environment)
    return TranslationTask(
        name=EXPERIMENT_NAME,
        checkpoint="last",
        model=create_model_with_mock_pretrained_model(config, model_provider_factory),
        environment=environment,
    )


def check_last_checkpoint_was_used(
    model_provider_factory: FixedTranslationPreTrainedModelProviderFactory, exp_dir: Path
):
    expected_checkpoint_dir = exp_dir / "run" / f"checkpoint-{CHECKPOINT_STEP}"
    assert model_provider_factory.inference_model_names == [str(expected_checkpoint_dir)]


def check_book_draft(exp_dir: Path, expected_translation: str) -> int:
    lines = read_lines(get_book_draft_path(exp_dir))
    assert lines[0] == f"\\id {BOOK}"

    # Every chapter of the draft is marked as machine generated
    remarks = [line for line in lines if line.startswith("\\rem ")]
    assert len(remarks) == 1
    assert remarks[0].startswith(f"\\rem This draft of {BOOK} 1 was generated by AI from project {SOURCE_PROJECT} on ")
    assert remarks[0].endswith(
        "It should be reviewed carefully for errors before use. "
        "Paragraph break positions were moved to the end of the verse."
    )

    verses = [line for line in lines if line.startswith("\\v ")]
    assert len(verses) > 0
    for verse in verses:
        assert verse.endswith(expected_translation)
    return len(verses)


def check_vref_export(exp_dir: Path, num_verses: int):
    # The --vref option additionally exports the draft in the original versification, which has
    # one line for every verse of the Bible and is therefore mostly empty.
    vref_lines = read_lines(get_book_draft_path(exp_dir).with_suffix(".txt"))
    assert len(vref_lines) > num_verses
    assert len([line for line in vref_lines if line != ""]) == num_verses


def check_book_confidences(exp_dir: Path, num_verses: int):
    confidences_path = get_book_draft_path(exp_dir).with_suffix(".SFM.confidences.tsv")

    sentence_confidences = read_verse_confidences(confidences_path)
    assert len(sentence_confidences) > num_verses
    for sentence_index, confidence in enumerate(sentence_confidences):
        assert confidence == pytest.approx(math.exp(mock_sequence_log_prob(sentence_index)), abs=1e-6)

    verse_confidences = read_confidences(confidences_path.with_suffix(".verses.tsv"), "VRef")
    assert len(verse_confidences) == num_verses
    assert all(key.startswith(f"{BOOK} 1:") for key in verse_confidences)
    assert set(verse_confidences.values()) <= set(sentence_confidences)

    chapter_confidences = read_confidences(confidences_path.with_suffix(".chapters.tsv"), "Chapter")
    assert list(chapter_confidences.keys()) == ["1"]

    book_confidences = read_confidences(confidences_path.parent / "confidences.books.tsv", "Book")
    assert list(book_confidences.keys()) == [BOOK]


def check_text_file_draft(exp_dir: Path, num_sentences: int, expected_translation: str):
    translations = read_lines(get_infer_dir(exp_dir) / SOURCE_FILE_NAME)
    assert translations == [expected_translation] * num_sentences


def check_text_file_confidences(exp_dir: Path, num_sentences: int):
    # Every line of a translated text file is translated as a single sentence, so the confidences
    # are the sequence scores that the mock model reported, in order.
    verse_confidences = read_confidences(
        get_infer_dir(exp_dir) / f"{SOURCE_FILE_NAME}.confidences.verses.tsv", "Sequence Number"
    )
    assert list(verse_confidences.keys()) == [str(index + 1) for index in range(num_sentences)]
    for index, confidence in enumerate(verse_confidences.values()):
        assert confidence == pytest.approx(math.exp(mock_sequence_log_prob(index)), abs=1e-6)

    file_confidences = read_confidences(get_infer_dir(exp_dir) / "confidences.files.tsv", "File")
    assert list(file_confidences.keys()) == [Path(SOURCE_FILE_NAME).stem]


def get_infer_dir(exp_dir: Path) -> Path:
    return exp_dir / "infer" / str(CHECKPOINT_STEP)


def get_book_draft_path(exp_dir: Path) -> Path:
    # The digits in the file name are the Paratext book number of the book
    return get_infer_dir(exp_dir) / SOURCE_PROJECT / f"{BOOK_NUMBER}{BOOK}.SFM"


def read_verse_confidences(path: Path) -> List[float]:
    rows: List[List[str]] = [line.split("\t") for line in read_lines(path)]
    assert rows[0][0] == "VRef"
    assert rows[1][0] == "Sequence Score"
    return [float(row[0]) for row in rows[3::2]]


def read_confidences(path: Path, expected_key_header: str) -> Dict[str, float]:
    rows: List[List[str]] = [line.split("\t") for line in read_lines(path)]
    assert rows[0] == [expected_key_header, "Confidence"]
    return {row[0]: float(row[1]) for row in rows[1:]}
